import requests

headers = {
    'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="99"',
    'Referer': 'https://www.zee5.com/',
    'sec-ch-ua-mobile': '?1',
    'Save-Data': 'on',
    'sec-ch-ua-platform': '"Android"',
    'Content-Type': 'application/x-www-form-urlencoded',
}

params = {
    'ip': '1',
    '_': '1648878262167',
}

data = 'data=eyIkc2V0IjogeyIkb3MiOiAiQW5kcm9pZCIsIiRicm93c2VyIjogIkNocm9tZSIsIiRicm93c2VyX3ZlcnNpb24iOiA5OSwiJGluaXRpYWxfcmVmZXJyZXIiOiAiaHR0cHM6Ly9yLnNlYXJjaC55YWhvby5jb20vX3lsdD1Bd3J4aFdpdjIwZGlNZ3NBalJXc25pTTU7X3lsdT1ZMjlzYndNRWNHOXpBekVFZG5ScFpBTUVjMlZqQTNOeS9SVj0yL1JFPTE2NDg5MDUyNjMvUk89MTAvUlU9aHR0cHMlM2ElMmYlMmZ3d3cuemVlNS5jb20lMmYvUks9Mi9SUz1kTGJJY3hUejZ5dE9McGZ5YTdfdjV1VWNiZWctIiwiJGluaXRpYWxfcmVmZXJyaW5nX2RvbWFpbiI6ICJyLnNlYXJjaC55YWhvby5jb20iLCJVbmlxdWUgSUQiOiAiOWEyNzVjMjYtNzFjNi00NmJiLWIzYTUtOTUyYThmNmE2MWRiIiwiUmVnaXN0cmluZyBDb3VudHJ5IjogIklOIiwiTmV3IEF1dG9wbGF5IFNldHRpbmciOiAidHJ1ZSIsIk5ldyBBcHAgTGFuZ3VhZ2UiOiAiZW4iLCJOZXcgQ29udGVudCBMYW5ndWFnZSI6IFsKICAgICJlbiIsCiAgICAidGUiCl0sIlVzZXIgVHlwZSI6ICJwcmVtaXVtIiwiTmV4dCBFeHBpcmluZyBQYWNrIjogWwogICAgIjAtMTEtMTg0Ml9QcmVtaXVtX1NWT0QiCl0sIk5leHQgUGFjayBFeHBpcnkgRGF0ZSI6ICIyMDIzLTAyLTE4VDIzOjU5OjU5WiIsIkZyZWUgVHJpYWwgRXhwaXJ5IERhdGUiOiAiTi9BIiwiUGFjayBEdXJhdGlvbiI6IDM2NSwiRnJlZSBUcmlhbCBQYWNrYWdlIjogIk4vQSIsIkdlbmRlciI6ICJNYWxlIiwiTGF0ZXN0IFN1YnNjcmlwdGlvbiBQYWNrIjogIjAtMTEtMTg0Ml9QcmVtaXVtX1NWT0QiLCJMYXRlc3QgU3Vic2NyaXB0aW9uIFBhY2sgRXhwaXJ5IjogIjIwMjMtMDItMThUMjM6NTk6NTlaIiwiUGFyZW50IENvbnRyb2wgU2V0dGluZyI6ICJOL0EiLCJBZ2UiOiAiTi9BIiwiUGFydG5lciBOYW1lIjogIlplZTUiLCJoYXNFZHVhdXJhYSI6IGZhbHNlLCJIYXNSZW50YWwiOiBmYWxzZX0sIiR0b2tlbiI6ICIyOGFkMWJkM2Y5ZmJjZGE3MzU2YzcwODM1YTBiNGQ5NiIsIiRkaXN0aW5jdF9pZCI6ICI5YTI3NWMyNi03MWM2LTQ2YmItYjNhNS05NTJhOGY2YTYxZGIiLCIkZGV2aWNlX2lkIjogIjE3ZmU4YjI0ZTU3NmVjLTAxNTZkMTIwYWMwZTg0LTI2NDI2YTEyLTUzYzMxLTE3ZmU4YjI0ZTU4N2U0IiwiJHVzZXJfaWQiOiAiOWEyNzVjMjYtNzFjNi00NmJiLWIzYTUtOTUyYThmNmE2MWRiIn0='

response = requests.post('https://api-js.mixpanel.com/engage/', headers=headers, params=params, data=data)
